-- Copy and paste this into the SQL Editor in your Supabase Dashboard

-- 1. Create a table for User Profiles
create table profiles (
  user_id uuid primary key, -- We will generate this in the app for now
  updated_at timestamp with time zone,
  name text,
  goal text,
  health_purpose text,
  height numeric,
  weight numeric,
  target_weight numeric,
  birth_date date,
  gender text,
  activity_level text,
  is_onboarded boolean
);

-- 2. Create a table for Daily Logs
create table daily_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(user_id) not null,
  date date not null,
  breakfast numeric default 0,
  lunch numeric default 0,
  dinner numeric default 0,
  snack numeric default 0,
  exercise numeric default 0,
  sleep numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, date) -- One log per user per day
);

-- 3. Enable Row Level Security (RLS) - Recommended for security
alter table profiles enable row level security;
alter table daily_logs enable row level security;

-- 4. Create Policies (For now, allow public access so it works without login)
-- WARNING: In a production app with real login, you would restrict this!
create policy "Public profiles access" on profiles for all using (true);
create policy "Public logs access" on daily_logs for all using (true);
